#spring:
#  application:
#    name: "templar-custodian"

server:
  port: 8090

---
spring:
  spring:
    application:
      name: "templar-custodian"
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:templarcustodian;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

#---
#spring:
#  config:
#    activate:
#      on-profile: postgres
#  datasource:
#    url: jdbc:postgresql://localhost:5432/templarcustodian
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: validate     # or none if you use migrations
#    show-sql: false
#    properties:
#      hibernate.jdbc.lob.non_contextual_creation: true
#      hibernate.format_sql: true