// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: protos/orders.proto

package orders

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderType int32

const (
	OrderType_MARKET OrderType = 0
	OrderType_LIMIT  OrderType = 1
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "MARKET",
		1: "LIMIT",
	}
	OrderType_value = map[string]int32{
		"MARKET": 0,
		"LIMIT":  1,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_orders_proto_enumTypes[0].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_protos_orders_proto_enumTypes[0]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_protos_orders_proto_rawDescGZIP(), []int{0}
}

type OrderSide int32

const (
	OrderSide_BUY  OrderSide = 0
	OrderSide_SELL OrderSide = 1
)

// Enum value maps for OrderSide.
var (
	OrderSide_name = map[int32]string{
		0: "BUY",
		1: "SELL",
	}
	OrderSide_value = map[string]int32{
		"BUY":  0,
		"SELL": 1,
	}
)

func (x OrderSide) Enum() *OrderSide {
	p := new(OrderSide)
	*p = x
	return p
}

func (x OrderSide) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderSide) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_orders_proto_enumTypes[1].Descriptor()
}

func (OrderSide) Type() protoreflect.EnumType {
	return &file_protos_orders_proto_enumTypes[1]
}

func (x OrderSide) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderSide.Descriptor instead.
func (OrderSide) EnumDescriptor() ([]byte, []int) {
	return file_protos_orders_proto_rawDescGZIP(), []int{1}
}

type PlaceOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraderId      string                 `protobuf:"bytes,1,opt,name=trader_id,json=traderId,proto3" json:"trader_id,omitempty"`
	StockSymbol   string                 `protobuf:"bytes,2,opt,name=stock_symbol,json=stockSymbol,proto3" json:"stock_symbol,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Type          OrderType              `protobuf:"varint,5,opt,name=type,proto3,enum=babylonexchange.orders.v1.OrderType" json:"type,omitempty"`
	Side          OrderSide              `protobuf:"varint,6,opt,name=side,proto3,enum=babylonexchange.orders.v1.OrderSide" json:"side,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceOrderRequest) Reset() {
	*x = PlaceOrderRequest{}
	mi := &file_protos_orders_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderRequest) ProtoMessage() {}

func (x *PlaceOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_orders_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderRequest.ProtoReflect.Descriptor instead.
func (*PlaceOrderRequest) Descriptor() ([]byte, []int) {
	return file_protos_orders_proto_rawDescGZIP(), []int{0}
}

func (x *PlaceOrderRequest) GetTraderId() string {
	if x != nil {
		return x.TraderId
	}
	return ""
}

func (x *PlaceOrderRequest) GetStockSymbol() string {
	if x != nil {
		return x.StockSymbol
	}
	return ""
}

func (x *PlaceOrderRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *PlaceOrderRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PlaceOrderRequest) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_MARKET
}

func (x *PlaceOrderRequest) GetSide() OrderSide {
	if x != nil {
		return x.Side
	}
	return OrderSide_BUY
}

type PlaceOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceOrderResponse) Reset() {
	*x = PlaceOrderResponse{}
	mi := &file_protos_orders_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderResponse) ProtoMessage() {}

func (x *PlaceOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_orders_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderResponse.ProtoReflect.Descriptor instead.
func (*PlaceOrderResponse) Descriptor() ([]byte, []int) {
	return file_protos_orders_proto_rawDescGZIP(), []int{1}
}

func (x *PlaceOrderResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

var File_protos_orders_proto protoreflect.FileDescriptor

const file_protos_orders_proto_rawDesc = "" +
	"\n" +
	"\x13protos/orders.proto\x12\x19babylonexchange.orders.v1\"\xf9\x01\n" +
	"\x11PlaceOrderRequest\x12\x1b\n" +
	"\ttrader_id\x18\x01 \x01(\tR\btraderId\x12!\n" +
	"\fstock_symbol\x18\x02 \x01(\tR\vstockSymbol\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x128\n" +
	"\x04type\x18\x05 \x01(\x0e2$.babylonexchange.orders.v1.OrderTypeR\x04type\x128\n" +
	"\x04side\x18\x06 \x01(\x0e2$.babylonexchange.orders.v1.OrderSideR\x04side\"/\n" +
	"\x12PlaceOrderResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId*\"\n" +
	"\tOrderType\x12\n" +
	"\n" +
	"\x06MARKET\x10\x00\x12\t\n" +
	"\x05LIMIT\x10\x01*\x1e\n" +
	"\tOrderSide\x12\a\n" +
	"\x03BUY\x10\x00\x12\b\n" +
	"\x04SELL\x10\x012y\n" +
	"\fOrderService\x12i\n" +
	"\n" +
	"PlaceOrder\x12,.babylonexchange.orders.v1.PlaceOrderRequest\x1a-.babylonexchange.orders.v1.PlaceOrderResponseBxZLgithub.com/lennardclaproth/ansar-broker/babylonexchange/protos/orders;orders\xaa\x02'PopcornMarket.BabylonExchange.Contractsb\x06proto3"

var (
	file_protos_orders_proto_rawDescOnce sync.Once
	file_protos_orders_proto_rawDescData []byte
)

func file_protos_orders_proto_rawDescGZIP() []byte {
	file_protos_orders_proto_rawDescOnce.Do(func() {
		file_protos_orders_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_orders_proto_rawDesc), len(file_protos_orders_proto_rawDesc)))
	})
	return file_protos_orders_proto_rawDescData
}

var file_protos_orders_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protos_orders_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_orders_proto_goTypes = []any{
	(OrderType)(0),             // 0: babylonexchange.orders.v1.OrderType
	(OrderSide)(0),             // 1: babylonexchange.orders.v1.OrderSide
	(*PlaceOrderRequest)(nil),  // 2: babylonexchange.orders.v1.PlaceOrderRequest
	(*PlaceOrderResponse)(nil), // 3: babylonexchange.orders.v1.PlaceOrderResponse
}
var file_protos_orders_proto_depIdxs = []int32{
	0, // 0: babylonexchange.orders.v1.PlaceOrderRequest.type:type_name -> babylonexchange.orders.v1.OrderType
	1, // 1: babylonexchange.orders.v1.PlaceOrderRequest.side:type_name -> babylonexchange.orders.v1.OrderSide
	2, // 2: babylonexchange.orders.v1.OrderService.PlaceOrder:input_type -> babylonexchange.orders.v1.PlaceOrderRequest
	3, // 3: babylonexchange.orders.v1.OrderService.PlaceOrder:output_type -> babylonexchange.orders.v1.PlaceOrderResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protos_orders_proto_init() }
func file_protos_orders_proto_init() {
	if File_protos_orders_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_orders_proto_rawDesc), len(file_protos_orders_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_orders_proto_goTypes,
		DependencyIndexes: file_protos_orders_proto_depIdxs,
		EnumInfos:         file_protos_orders_proto_enumTypes,
		MessageInfos:      file_protos_orders_proto_msgTypes,
	}.Build()
	File_protos_orders_proto = out.File
	file_protos_orders_proto_goTypes = nil
	file_protos_orders_proto_depIdxs = nil
}
