FINANCIAL_TIMES = "https://localhost:7236/api/v1/articles"  # Replace with actual API URL
COMPANY_ARTICLES_ENDPOINT = f"{FINANCIAL_TIMES}/company"
POLITICAL_ARTICLES_ENDPOINT = f"{FINANCIAL_TIMES}/political"
MACRO_ARTICLES_ENDPOINT = f"{FINANCIAL_TIMES}/macro"
SECTOR_ARTICLES_ENDPOINT = f"{FINANCIAL_TIMES}/sector"
PUBLISH_ARTICLE_ENDPOINT = f"{FINANCIAL_TIMES}/publish"
TICKERS_ENDPOINT = f"{FINANCIAL_TIMES}/tickers"
