FINANCIAL_ATLAS = "https://localhost:7087/api/v1"
COMPANY_ENDPOINT=f"{FINANCIAL_ATLAS}/company"
FINANCIAL_STATEMENT_ENDPOINT=f"{FINANCIAL_ATLAS}/financial-statement"
MARKET_DATA_ENDPOINT=f"{FINANCIAL_ATLAS}/market-data"
TICKERS_ENDPOINT = f"{FINANCIAL_ATLAS}/company/tickers"

SERVICE_DESC = f"PopcornMarket.FinancialAtlas"