// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PopcornMarket.BabylonExchange.Persistence.Context;

#nullable disable

namespace PopcornMarket.BabylonExchange.Persistence.Migrations
{
    [DbContext(typeof(BabylonExchangeDbContext))]
    partial class BabylonExchangeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("PopcornMarket.BabylonExchange.Domain.Entities.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UUID");

                    b.Property<string>("Isin")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Listing", "OrderBook");
                });

            modelBuilder.Entity("PopcornMarket.BabylonExchange.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("UUID");

                    b.Property<DateTime?>("ExecutedTimestamp")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<decimal>("ExecutionPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("NUMERIC(18,6)");

                    b.Property<Guid>("OrderBookId")
                        .HasColumnType("UUID");

                    b.Property<int>("OrderSide")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PlacedTimestamp")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 6)
                        .HasColumnType("NUMERIC(18,6)");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RemainingQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StockSymbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("TraderId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExecutedTimestamp");

                    b.HasIndex("OrderBookId");

                    b.HasIndex("PlacedTimestamp");

                    b.ToTable("Order", "OrderBook");
                });

            modelBuilder.Entity("PopcornMarket.BabylonExchange.Domain.Entities.OrderBook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UUID");

                    b.Property<decimal?>("CurrentPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("NUMERIC(18,6)");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("UUID");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ListingId")
                        .IsUnique();

                    b.HasIndex("Ticker");

                    b.ToTable("OrderBook", "OrderBook");
                });

            modelBuilder.Entity("PopcornMarket.BabylonExchange.Domain.Entities.Order", b =>
                {
                    b.HasOne("PopcornMarket.BabylonExchange.Domain.Entities.OrderBook", "OrderBook")
                        .WithMany("Orders")
                        .HasForeignKey("OrderBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderBook");
                });

            modelBuilder.Entity("PopcornMarket.BabylonExchange.Domain.Entities.OrderBook", b =>
                {
                    b.HasOne("PopcornMarket.BabylonExchange.Domain.Entities.Listing", "Listing")
                        .WithOne("OrderBook")
                        .HasForeignKey("PopcornMarket.BabylonExchange.Domain.Entities.OrderBook", "ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("PopcornMarket.BabylonExchange.Domain.Entities.Listing", b =>
                {
                    b.Navigation("OrderBook");
                });

            modelBuilder.Entity("PopcornMarket.BabylonExchange.Domain.Entities.OrderBook", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
